remote_theme: knhash/jekyllBear
title: "Erin White - UX, IA, a11y, etc etc"
name: "Erin White - UX, IA, a11y, etc etc"

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/

plugins:
  - jekyll-feed

feed:
  path: /feed
  tags: true
    path: /:slug/feed

defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

links:
  About: /about
  Colophon: /colophon
