remote_theme: knhash/jekyllBear
sit.title: "Erin White - UX, IA, a11y, etc etc"
title: "Erin White"

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/


defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

links:
  About: /about
  Colophon: /colophon
