remote_theme: knhash/jekyllBear
title: "Erin White"
name: "Erin White"

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  tags: true

defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

links:
  Home: /
  About: /about
  Site info + accessibility: /site-info
